workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60

    environment:
      vars:
        APP_STORE_API_KEY: $APP_STORE_API_KEY  # Sørg for at denne er satt i Codemagic miljøvariabler
      xcode: latest  # Bruk siste versjon av Xcode, eller spesifiser f.eks. "14.2"

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod install

      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace YourApp.xcworkspace \
            -scheme YourAppScheme \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/YourApp.xcarchive \
            archive

      - name: Export .ipa file
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/YourApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY  # Sørg for at API-nøkkelen er riktig konfigurert i Codemagic
