workflows:
  ios:
    name: iOS Workflow
    max_build_duration: 60
    trigger:
      events:
        - push
        - pull_request
    build:
      ios:
        app_bundle_id: com.example.kitchenapp # Sett inn ditt faktiske app bundle ID
        ios_simulator: true
    publish:
      app_store:
        api_key: $APP_STORE_API_KEY # Sørg for at du har riktig API-nøkkel for App Store
