workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60

    environment:
      ruby: 3.0.4
      vars:
        APP_STORE_API_KEY: $APP_STORE_API_KEY
        APP_STORE_KEY_ID: $APP_STORE_KEY_ID
        APP_STORE_ISSUER_ID: $APP_STORE_ISSUER_ID
      xcode: latest

    scripts:
      - name: Update ruby-build
        script: |
          brew update && brew upgrade ruby-build

      - name: Install Ruby 3.0.4
        script: |
          rbenv install 3.0.4 --skip-existing
          rbenv global 3.0.4
          ruby -v

      - name: Ensure rbenv is active
        script: |
          eval "$(rbenv init -)"
          rbenv rehash
          ruby -v

      - name: Install CocoaPods
        script: |
          gem install cocoapods --user-install
          pod --version

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --verbose || { echo 'pod install feilet'; exit 1; }

      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace ios/KitchenApp.xcworkspace \
            -scheme KitchenApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/KitchenApp.xcarchive \
            archive || { echo 'Build feilet'; exit 1; }

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
