workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60

    environment:
      vars:
        APP_STORE_API_KEY: $APP_STORE_API_KEY
        APP_STORE_KEY_ID: $APP_STORE_KEY_ID
        APP_STORE_ISSUER_ID: $APP_STORE_ISSUER_ID
      xcode: latest  

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install CocoaPods dependencies
        script: |
          sudo gem install cocoapods
          cd ios
          if [ ! -f "Podfile" ]; then
            pod init  # Opprett Podfile hvis den ikke finnes
          fi
          pod install

      - name: Build iOS app
        script: |
          xcodebuild \
            -workspace ios/YourApp.xcworkspace \
            -scheme YourAppScheme \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/YourApp.xcarchive \
            archive

      - name: Export .ipa file
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/YourApp.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - ios/build/*.ipa  

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
