workflows:
  ios-workflow:
    name: iOS Workflow
    description: Build and publish iOS app
    envs:
      - APP_STORE_API_KEY: $APP_STORE_API_KEY  # Ensure this is set in Bitrise secrets
    steps:
      - git-clone: {}
      - script:
          title: Set up Xcode
          inputs:
            - content: |
                #!/bin/bash
                sudo xcode-select --switch /Applications/Xcode_14.2.app
                xcodebuild -version
      - script:
          title: Install dependencies
          inputs:
            - content: |
                #!/bin/bash
                brew install cocoapods
                pod install
      - xcode-build:
          inputs:
            - project_path: YourApp.xcworkspace
            - scheme: YourAppScheme
            - configuration: Release
            - sdk: iphoneos
            - code_sign_identity: "iPhone Distribution"
            - development_team: YOUR_TEAM_ID
            - provisioning_profile_specifier: "Your_Provisioning_Profile"
      - script:
          title: Publish to App Store
          inputs:
            - content: |
                #!/bin/bash
                xcodebuild \
                  -exportArchive \
                  -archivePath YourApp.xcarchive \
                  -exportOptionsPlist ExportOptions.plist \
                  -exportPath . \
                  -allowProvisioningUpdates