workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60

    environment:
      ruby: 3.3.7  # Sikrer at riktig Ruby-versjon brukes
      vars:
        APP_STORE_API_KEY: $APP_STORE_API_KEY
        APP_STORE_KEY_ID: $APP_STORE_KEY_ID
        APP_STORE_ISSUER_ID: $APP_STORE_ISSUER_ID
      xcode: latest  

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install CocoaPods dependencies
        script: |
          echo "Oppdaterer CocoaPods..."
          gem install cocoapods --user-install
          export PATH=$HOME/.gem/ruby/3.3.7/bin:$PATH

          echo "Installerer Pods..."
          cd ios
          pod install --verbose || { echo 'Pod install feilet'; exit 1; }

      - name: Build iOS app
        script: |
          echo "Bygger iOS-appen..."
          xcodebuild \
            -workspace ios/KitchenApp.xcworkspace \
            -scheme KitchenApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/KitchenApp.xcarchive \
            archive || { echo 'Build feilet'; exit 1; }

      - name: Export .ipa file
        script: |
          echo "Eksporterer .ipa..."
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/KitchenApp.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR || { echo 'Export feilet'; exit 1; }

    artifacts:
      - build/ios/ipa/*.ipa  

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID

