workflows:
  ios:
    name: iOS Workflow
    trigger:
      events:
        - push
        - pull_request
      branches:
        only:
          - main  # Kjør kun på push til main-grenen
    build:
      ios:
        app_id: 1:959701393192:ios:b9c497d2a3898195acba1d
        development_team: YOUR_TEAM_ID  # Sett inn ditt team ID
        provisioning_profile: "path/to/profile"  # Valgfritt, hvis du bruker en spesifikk provisioning profile
        distribution_certificate: "path/to/certificate"  # Valgfritt, hvis du har et spesifikt sertifikat
    publish:
      app_store:
        api_key: AIzaSyDNPgh24lOoXZFMu9_QQd5BDCEoSv2c88A
