workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    environment:
      xcode: 16.2
      cocoapods: default
      ruby: 3.1.0
      vars:
        APP_STORE_API_KEY: $APP_STORE_API_KEY
        APP_STORE_ISSUER_ID: $APP_STORE_ISSUER_ID
        APP_STORE_KEY_ID: $APP_STORE_KEY_ID
    scripts:
      - name: Set up Ruby and CocoaPods
        script: |
          rbenv install --skip-existing 3.1.0
          rbenv global 3.1.0
          gem install bundler
          bundle install
          cd ios
          pod install

      - name: Build iOS app
        script: |
          xcode-project use-ios-workspace
          xcode-project build-ipa --workspace "ios/KitchenApp.xcworkspace" --scheme "KitchenApp"

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
