# Denne Podfile er for et iOS-prosjekt
platform :ios, '12.0'  # Sett minimum iOS-versjon
use_frameworks!  # Bruk dynamiske rammeverk

# Sett prosjektet ditt her hvis du har en spesifikk prosjektfil
# project 'path/to/YourProject.xcodeproj' 

# Targeten for prosjektet ditt (dvs. applikasjonen)
target 'KitchenApp' do
  # Legg til avhengigheter for prosjektet ditt her
  pod 'Alamofire', '~> 5.0'  # Eksempel på en pod (kan være en hvilken som helst avhengighet)
  pod 'Firebase/Analytics'   # Legg til Firebase eller andre nødvendige pods

  # Hvis du bruker flere targets (for eksempel en test target), kan du spesifisere dem også
  # target 'KitchenAppTests' do
  #   pod 'Nimble'
  # end
end
